service:
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD = yes
    ports:
      - '6379':'6379'
        
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  
  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    port:
      - "19411:9411"
        
  # Prometheus
    prometheus:
      container_name: prometheus
      image: pro/prometheus:latest
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
          
  # OTEL
  otel-collector:
    image: otel/opentelemetry-collector:0.55.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof 扩展端口
      - "8888:8888"   # otel 暴露的 Prometheus 端口
      - "8889:8889"   # Prometheus exporter 端口
      - "13133:13133" # 健康检查扩展
      - "4317:4317"   # OTLP gRPC 接收器端口
      - "4318:4318"   # OTLP http 接收器端口
      - "55679:55679" # zpages 扩展端口
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one